# Generated by Django 5.1.6 on 2025-03-01 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('logo_img_src', models.URLField(max_length=500)),
                ('main_img_src', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('logo_img_src', models.URLField(max_length=500)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='CategorisApi.maincategory')),
            ],
        ),
    ]
