# Generated by Django 5.1.6 on 2025-03-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CategorisApi', '0002_remove_maincategory_title_remove_subcategory_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='main_category',
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
