# Generated by Django 5.1.6 on 2025-03-02 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CategorisApi', '0005_remove_subcategory_main_category_delete_maincategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subtitle', models.CharField(max_length=150)),
                ('logo_img', models.ImageField(upload_to='logos/')),
                ('main_img', models.ImageField(upload_to='main_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subtitle', models.CharField(max_length=150)),
                ('logo_img', models.ImageField(upload_to='logos/')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='CategorisApi.maincategory')),
            ],
        ),
    ]
