# Generated by Django 5.1.6 on 2025-03-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CategorisApi', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='main_category',
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
