# Generated by Django 5.1.6 on 2025-04-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='avatar', max_length=15),
        ),
    ]
